const mongoose = require('mongoose');
const dotenv = require('dotenv');
const MenuItem = require('../models/MenuItem');

dotenv.config();

const categoryMap = {
  'Rice': '69c8fc9916990b857678749c',
  'Rice & Biryani': '69c8fc9916990b857678749c',
  'Ice Cream': '69c927dd16990b85767874da',
  'Salad': '69c927dd16990b85767874db',
  'Lassi & Desserts': '69c8fc9916990b85767874a1',
  'Fresh Shakes': '69c8fc9916990b85767874a1',
  'Fresh Juices': '69c8fc9916990b85767874a0',
  'Beverages': '69c8fc9916990b85767874a0',
  'Breakfast': '69c927dd16990b85767874dc',
  'Cold Drinks': '69c8fc9916990b85767874a0',
  'Burgers': '69c8fc9916990b857678749e',
  'Broast': '69c927dd16990b85767874dd',
  'Sandwiches': '69c927dd16990b85767874de',
  'Shawarma/Rolls': '69c927dd16990b85767874df',
  'French Fries/Finger Fish': '69c927dd16990b85767874e0',
  'Wings/Tortilla Wraps': '69c927dd16990b85767874e0',
  'Pizza': '69c8fc9916990b857678749b',
  'Special Dishes': '69c8fc9916990b8576787498',
  'Karahi': '69c8fc9916990b857678749a',
  'B.B.Q': '69c8fc9916990b8576787499',
  'Handi': '69c8fc9916990b857678749a'
};

const items = [
  { name: "Kabli Pulao", category: "Rice", price: 450, description: "Traditional Afghan-style rice cooked with tender mutton, carrots, raisins, and aromatic spices. A signature dish loved in Kohat." },
  { name: "Karachi Biryani", category: "Rice", price: 380, description: "Spicy and flavorful biryani made with tender chicken, aromatic basmati rice, and special Karachi-style masala. Served with raita." },
  { name: "Champ Roash", category: "Rice", price: 520, description: "Juicy mutton chops cooked to perfection and served with steamed rice and special gravy. A Kohat specialty." },
  { name: "Qeema", category: "Rice", price: 320, description: "Finely minced beef cooked with peas, onions, and traditional spices. Served with plain rice or naan." },
  { name: "Chicken Korma", category: "Rice", price: 350, description: "Creamy and rich chicken curry cooked in yogurt-based gravy with aromatic spices. Perfect with rice." },
  { name: "Daal Channa", category: "Rice", price: 220, description: "Protein-rich black chickpeas slow-cooked with ginger, garlic, and traditional spices. A healthy comfort food." },
  { name: "Sabzi", category: "Rice", price: 200, description: "Seasonal mixed vegetables cooked with light spices. A simple yet delicious side dish." },
  { name: "Pista Ice Cream", category: "Ice Cream", price: 80, description: "Creamy pistachio-flavored ice cream made with real pistachios. Perfect for dessert lovers." },
  { name: "Kolfa Ice Cream", category: "Ice Cream", price: 80, description: "Traditional kulfi-style ice cream with rich malai flavor and cardamom essence." },
  { name: "Blue Berry Ice Cream", category: "Ice Cream", price: 80, description: "Refreshing blueberry-flavored ice cream with a fruity twist. Kids favorite." },
  { name: "Chocolate Ice Cream", category: "Ice Cream", price: 80, description: "Rich and creamy chocolate ice cream made with premium cocoa. A classic treat." },
  { name: "Strawberry Ice Cream", category: "Ice Cream", price: 80, description: "Sweet and tangy strawberry ice cream with real fruit flavor. Perfect for summer." },
  { name: "Vanilla Ice Cream", category: "Ice Cream", price: 80, description: "Classic vanilla bean ice cream smooth and creamy. Pairs well with any dessert." },
  { name: "Bounty Ice Cream", category: "Ice Cream", price: 80, description: "Coconut and chocolate combination ice cream inspired by bounty bar taste." },
  { name: "Mango Ice Cream", category: "Ice Cream", price: 80, description: "Fresh mango-flavored ice cream capturing the essence of Pakistani mangoes." },
  { name: "Extra Topping", category: "Ice Cream", price: 50, description: "Add extra chocolate sauce, nuts, sprinkles, or fresh fruits to your ice cream." },
  { name: "Russian Salad", category: "Salad", price: 350, description: "Creamy salad with boiled vegetables, apples, and mayonnaise dressing. Served chilled." },
  { name: "Fresh Vegetable Salad", category: "Salad", price: 80, description: "Fresh cucumber, tomato, onion, and carrot with lemon and chaat masala." },
  { name: "Fresh Raita", category: "Salad", price: 80, description: "Yogurt mixed with finely chopped cucumber, mint, and roasted cumin powder." },
  { name: "Fruit Punch", category: "Salad", price: 400, description: "Fresh seasonal fruits tossed in a tangy dressing. Refreshing and healthy." },
  { name: "Fruit Special Chat", category: "Salad", price: 350, description: "Mixed fruits with chaat masala, tamarind sauce, and crispy papri. Sweet and tangy." },
  { name: "Special Ice Cream Shake", category: "Lassi & Desserts", price: 300, description: "Thick shake made with vanilla ice cream, milk, and your choice of flavor." },
  { name: "Special Kit Kat Shake", category: "Lassi & Desserts", price: 350, description: "Crushed Kit Kat blended with ice cream and milk. Topped with chocolate sauce." },
  { name: "Special Snickers Shake", category: "Lassi & Desserts", price: 350, description: "Caramel peanut chocolate shake with Snickers bar blended in. Rich and filling." },
  { name: "Special Mars Shake", category: "Lassi & Desserts", price: 350, description: "Caramel chocolate malt shake with Mars bar. A sweet indulgence." },
  { name: "Special Oreo Shake", category: "Lassi & Desserts", price: 350, description: "Crushed Oreo cookies blended with vanilla ice cream and milk. Cookies and cream delight." },
  { name: "Special Bounty Shake", category: "Lassi & Desserts", price: 350, description: "Coconut chocolate shake with Bounty bar. Tropical and creamy." },
  { name: "Special Protein Shake", category: "Lassi & Desserts", price: 350, description: "High-protein shake with whey protein, banana, and peanut butter. Fitness friendly." },
  { name: "Special Fresh Fruit Shake", category: "Lassi & Desserts", price: 200, description: "Fresh seasonal fruits blended with milk and a touch of sugar. Pure and natural." },
  { name: "Apple Fresh Shake", category: "Fresh Shakes", price: 250, description: "Fresh apple blended with chilled milk and a hint of cinnamon. Refreshing drink." },
  { name: "Mango Fresh Shake", category: "Fresh Shakes", price: 250, description: "Ripe seasonal mangoes blended with milk. A summer favorite in Kohat." },
  { name: "Banana Fresh Shake", category: "Fresh Shakes", price: 250, description: "Ripe bananas blended with milk and honey. Creamy and energizing." },
  { name: "Peach Fresh Shake", category: "Fresh Shakes", price: 300, description: "Sweet peach puree blended with yogurt and milk. Smooth and fruity." },
  { name: "Papaya Fresh Shake", category: "Fresh Shakes", price: 300, description: "Fresh papaya blended with milk and a touch of honey. Digestive friendly." },
  { name: "Strawberry Fresh Shake", category: "Fresh Shakes", price: 300, description: "Fresh strawberries blended with milk and sugar. Sweet and tangy." },
  { name: "Fresh Lime Juice", category: "Fresh Juices", price: 250, description: "Freshly squeezed lime with sugar, salt, and chilled water. Classic refresher." },
  { name: "Mint Lemonade", category: "Fresh Juices", price: 250, description: "Fresh mint leaves blended with lime juice and sugar. Cool and refreshing." },
  { name: "Pomegranate Juice", category: "Fresh Juices", price: 400, description: "Freshly pressed pomegranate seeds. Rich in antioxidants and flavor." },
  { name: "Carrot Juice", category: "Fresh Juices", price: 200, description: "Fresh carrot juice with a hint of ginger. Healthy and nutritious." },
  { name: "Apple Juice", category: "Fresh Juices", price: 250, description: "Fresh apple juice without added sugar. Pure and natural." },
  { name: "Orange Juice", category: "Fresh Juices", price: 250, description: "Freshly squeezed oranges. Vitamin C rich and energizing." },
  { name: "Plum Juice", category: "Fresh Juices", price: 250, description: "Sweet and tangy alu bukhara juice. Traditional favorite." },
  { name: "Falsa Juice", category: "Fresh Juices", price: 300, description: "Seasonal falsa berry juice with black salt. Perfect for hot days." },
  { name: "Mango Lassi", category: "Fresh Juices", price: 200, description: "Sweet mango pulp blended with thick yogurt. Creamy and satisfying." },
  { name: "Plain Lassi", category: "Fresh Juices", price: 150, description: "Traditional yogurt drink blended with sugar or salt. Smooth and cooling." },
  { name: "Lemon Water", category: "Fresh Juices", price: 200, description: "Fresh lemon juice with sugar and water. Simple and refreshing." },
  { name: "Plain Paratha", category: "Breakfast", price: 60, description: "Layered flatbread fried to golden perfection. Served with chai." },
  { name: "Tandoori Paratha", category: "Breakfast", price: 80, description: "Whole wheat flatbread baked in tandoor. Crispy outside soft inside." },
  { name: "Omelette", category: "Breakfast", price: 120, description: "Three-egg omelette with onions, tomatoes, and green chilies. Served with paratha." },
  { name: "Gur Tea", category: "Breakfast", price: 100, description: "Black tea sweetened with jaggery. Traditional Kohat breakfast drink." },
  { name: "Malai", category: "Breakfast", price: 100, description: "Fresh thick cream served with bread or paratha. Rich and creamy." },
  { name: "Doodh Pati Chai", category: "Breakfast", price: 70, description: "Strong milk tea without water. Rich and creamy Pakistani style." },
  { name: "Green Tea", category: "Breakfast", price: 50, description: "Light and healthy green tea. Good for digestion." },
  { name: "Egg Fry", category: "Breakfast", price: 60, description: "Sunny side up egg fried in butter. Served with paratha." },
  { name: "Coffee", category: "Breakfast", price: 150, description: "Freshly brewed coffee with milk and sugar. Energizing start." },
  { name: "Kashmiri Chai", category: "Breakfast", price: 150, description: "Pink tea with nuts and cardamom. Traditional Kashmiri style." },
  { name: "Plain Naan", category: "Breakfast", price: 40, description: "Soft tandoor-baked flatbread. Perfect with any curry." },
  { name: "Chapati", category: "Breakfast", price: 80, description: "Whole wheat hand-made flatbread. Healthy and wholesome." },
  { name: "Cold Drink Regular", category: "Cold Drinks", price: 70, description: "Regular sized soft drink. Pepsi, Coca-Cola, or 7Up available." },
  { name: "Cold Drink 1 Liter", category: "Cold Drinks", price: 170, description: "One liter bottle. Perfect for sharing." },
  { name: "Cold Drink 1.5 Liter", category: "Cold Drinks", price: 220, description: "Large bottle for family or group." },
  { name: "Cold Drink Jumbo", category: "Cold Drinks", price: 300, description: "Extra large bottle. Best value for parties." },
  { name: "Sting Regular", category: "Cold Drinks", price: 80, description: "Carbonated energy drink with caffeine and ginseng." },
  { name: "Sting Disposable", category: "Cold Drinks", price: 130, description: "Larger disposable bottle of Sting energy drink." },
  { name: "Soft Drink Can", category: "Cold Drinks", price: 130, description: "Chilled canned soft drink. Easy to carry." },
  { name: "Zinger Burger", category: "Burgers", price: 480, description: "Crispy fried chicken fillet with lettuce and mayo in a sesame bun." },
  { name: "Zinger Cheese Burger", category: "Burgers", price: 520, description: "Crispy zinger fillet with melted cheese, lettuce, and special sauce." },
  { name: "Zinger Double Cheese Burger", category: "Burgers", price: 570, description: "Double zinger fillet with double cheese and extra sauce. For big appetite." },
  { name: "Beef Burger", category: "Burgers", price: 480, description: "Grilled beef patty with lettuce, tomato, onion, and burger sauce." },
  { name: "Beef Cheese Burger", category: "Burgers", price: 520, description: "Juicy beef patty with melted cheese, fresh veggies, and special sauce." },
  { name: "Chicken Grill Burger", category: "Burgers", price: 650, description: "Grilled chicken breast marinated in herbs. Healthy and delicious." },
  { name: "Chicken Grill Cheese Burger", category: "Burgers", price: 700, description: "Grilled chicken with melted cheese and garlic mayo sauce." },
  { name: "Peri Peri Burger", category: "Burgers", price: 480, description: "Spicy peri peri chicken fillet with lettuce and peri mayo sauce." },
  { name: "Fish Zinger Burger", category: "Burgers", price: 620, description: "Crispy fried fish fillet with tartar sauce and lettuce." },
  { name: "Fish Zinger Cheese Burger", category: "Burgers", price: 680, description: "Fish fillet with melted cheese and creamy sauce. Seafood delight." },
  { name: "Quarter Broast", category: "Broast", price: 550, description: "One piece of crispy fried chicken served with fries and garlic sauce." },
  { name: "Garlic Broast", category: "Broast", price: 580, description: "Crispy broast chicken tossed in garlic butter sauce. Aromatic and flavorful." },
  { name: "Cheese Broast", category: "Broast", price: 600, description: "Broast chicken topped with melted cheese. Rich and indulgent." },
  { name: "Masala Broast", category: "Broast", price: 550, description: "Crispy chicken coated with spicy masala. For spice lovers." },
  { name: "Full Broast", category: "Broast", price: 2100, description: "Whole chicken broast with fries, coleslaw, and garlic sauce. Family meal." },
  { name: "Club Sandwich", category: "Sandwiches", price: 480, description: "Triple-layer sandwich with chicken, lettuce, tomato, and mayo." },
  { name: "Club Cheese Sandwich", category: "Sandwiches", price: 520, description: "Club sandwich with extra cheese and grilled chicken. Hearty meal." },
  { name: "BBQ Sandwich", category: "Sandwiches", price: 550, description: "Grilled BBQ chicken with caramelized onions and BBQ sauce." },
  { name: "BBQ Cheese Sandwich", category: "Sandwiches", price: 590, description: "BBQ chicken sandwich with melted cheddar and mozzarella." },
  { name: "Tikka Sandwich", category: "Sandwiches", price: 550, description: "Chicken tikka pieces with mint chutney and fresh vegetables." },
  { name: "Tikka Cheese Sandwich", category: "Sandwiches", price: 580, description: "Chicken tikka with melted cheese and spicy mayo." },
  { name: "Crispy Chicken Sandwich", category: "Sandwiches", price: 480, description: "Crispy fried chicken fillet with lettuce and honey mustard." },
  { name: "Crispy Chicken Cheese Sandwich", category: "Sandwiches", price: 530, description: "Crispy chicken with cheese and creamy sauce. Kids favorite." },
  { name: "Chicken Shawarma", category: "Shawarma/Rolls", price: 250, description: "Grilled chicken wrapped in pita with garlic sauce and pickles." },
  { name: "Chicken Cheese Shawarma", category: "Shawarma/Rolls", price: 300, description: "Chicken shawarma with melted cheese and extra garlic sauce." },
  { name: "Zinger Shawarma", category: "Shawarma/Rolls", price: 300, description: "Crispy zinger fillet wrapped with fresh veggies and special sauce." },
  { name: "Zinger Cheese Shawarma", category: "Shawarma/Rolls", price: 320, description: "Zinger shawarma with melted cheese and spicy mayo." },
  { name: "Zinger Paratha Roll", category: "Shawarma/Rolls", price: 300, description: "Crispy zinger wrapped in soft paratha with chutney and onions." },
  { name: "Zinger Cheese Paratha Roll", category: "Shawarma/Rolls", price: 330, description: "Zinger roll with cheese and extra sauce in flaky paratha." },
  { name: "Chicken Paratha Roll", category: "Shawarma/Rolls", price: 300, description: "Grilled chicken pieces wrapped in paratha with mint chutney." },
  { name: "Chicken Cheese Paratha Roll", category: "Shawarma/Rolls", price: 320, description: "Chicken roll with melted cheese and spicy sauce. Filling meal." },
  { name: "Loaded Fries", category: "French Fries/Finger Fish", price: 700, description: "Crispy fries topped with cheese sauce, chicken chunks, and jalapenos." },
  { name: "Mayo Garlic Fries", category: "French Fries/Finger Fish", price: 330, description: "Fresh fries tossed in garlic mayo and herbs." },
  { name: "Masala Fries", category: "French Fries/Finger Fish", price: 300, description: "Crispy fries sprinkled with chaat masala and spices." },
  { name: "Plain Fries", category: "French Fries/Finger Fish", price: 280, description: "Classic crispy french fries. Served with ketchup." },
  { name: "Thousand Island Fries", category: "French Fries/Finger Fish", price: 350, description: "Fries topped with thousand island sauce and herbs." },
  { name: "Finger Fish 4 Pcs", category: "French Fries/Finger Fish", price: 650, description: "Crispy fish fingers served with tartar sauce and fries." },
  { name: "Finger Fish 12 Pcs", category: "French Fries/Finger Fish", price: 1800, description: "Family portion of crispy fish fingers with sauces." },
  { name: "Koila BBQ Wings", category: "Wings/Tortilla Wraps", price: 450, description: "Charcoal-grilled wings with smoky BBQ flavor. Served with dip." },
  { name: "BBQ Wings", category: "Wings/Tortilla Wraps", price: 450, description: "Grilled chicken wings basted in tangy BBQ sauce." },
  { name: "Buffalo Wings", category: "Wings/Tortilla Wraps", price: 500, description: "Spicy buffalo sauce coated wings. Served with blue cheese dip." },
  { name: "Hot Wings", category: "Wings/Tortilla Wraps", price: 450, description: "Extra spicy hot wings for heat lovers. Served with cooling dip." },
  { name: "Tender Juicy Chicken", category: "Wings/Tortilla Wraps", price: 600, description: "Crispy chicken tenders served with fries and honey mustard." },
  { name: "Beef Jumbo Wrap", category: "Wings/Tortilla Wraps", price: 499, description: "Large tortilla wrap with grilled beef, veggies, and special sauce." },
  { name: "Chicken Jumbo Wrap", category: "Wings/Tortilla Wraps", price: 449, description: "Large wrap with grilled chicken, lettuce, and garlic sauce." },
  { name: "Hot Dog Wrap", category: "Wings/Tortilla Wraps", price: 449, description: "Tortilla wrapped around beef sausage with cheese and sauces." },
  { name: "Mint Margarita", category: "Beverages", price: 250, description: "Refreshing mint lemonade with crushed ice. Perfect cooler." },
  { name: "Red Bull", category: "Beverages", price: 300, description: "Energy drink for an instant boost." },
  { name: "Sting 500ml", category: "Beverages", price: 130, description: "Carbonated energy drink. Refreshing and energizing." },
  { name: "Fresh Lime", category: "Beverages", price: 250, description: "Freshly squeezed lime juice with salt and sugar." },
  { name: "Fresh Lassi", category: "Beverages", price: 150, description: "Thick yogurt drink with sugar or salt. Cooling and filling." },
  { name: "Slice Juice", category: "Beverages", price: 100, description: "Packaged mango juice drink. Sweet and refreshing." },
  { name: "Texas Special Deep Dish Pizza", category: "Pizza", price: 1160, description: "Deep dish pizza with special red sauce, juicy chicken, extra cheese, jalapeno, sweet corn, mushroom, capsicum, olives. Loaded with toppings." },
  { name: "Alfredo Texas Special Pizza", category: "Pizza", price: 1160, description: "White sauce pizza with special alfredo sauce, juicy chicken, extra cheese, jalapeno, sweet corn, mushroom, capsicum, olives. Creamy and rich." },
  { name: "Chicken Supreme Pizza", category: "Pizza", price: 1160, description: "Smoke chicken, chicken sausages, special tomato sauce, mushroom, black olives, green peppers, onion, cheese. Classic supreme." },
  { name: "Beef Loaded Pizza", category: "Pizza", price: 1160, description: "Loaded beef toppings with special red sauce, mushroom, onion, olives, capsicum, cheese. For meat lovers." },
  { name: "Chicken Tikka Pizza", category: "Pizza", price: 1160, description: "Special creamy sauce, chicken tikka, beef pepperoni, mushroom, olives, cheese. Fusion of desi and Italian." },
  { name: "Black Pepper Pizza", category: "Pizza", price: 1160, description: "Special red sauce, butter, black pepper chicken, capsicum, mushroom, olives, cheese. Mildly spiced." },
  { name: "Fajita Pizza", category: "Pizza", price: 1160, description: "Tomato sauce, fajita chicken, mushroom, olives, cheese, onion. Southwestern flavors." },
  { name: "Smoke BBQ Pizza", category: "Pizza", price: 1160, description: "Special BBQ red sauce, smoke BBQ chicken, mushroom, capsicum, olives, cheese. Smoky and sweet." },
  { name: "Pepperoni Pizza", category: "Pizza", price: 1160, description: "Special tomato sauce, pepperoni, beef or chicken, mushroom, olives, cheese. Classic favorite." },
  { name: "Cheese & Tomato Pizza", category: "Pizza", price: 1160, description: "Special sauce, extra cheese, fresh tomato slices, oregano. Simple and delicious." },
  { name: "Mayo Crust Pizza", category: "Pizza", price: 1750, description: "Stuffed crust pizza with chicken tikka, special sauce, pineapple, mushroom, olives. Choice of smoke or fajita." },
  { name: "Crown Crust Pizza", category: "Pizza", price: 1750, description: "Crown-shaped stuffed crust with tomato sauce, capsicum, mushroom, olives, sweet corn, cucumber, onion." },
  { name: "Special Koila Matka Pizza", category: "Pizza", price: 2300, description: "Charcoal-fired matka style pizza served in clay pot. Premium ingredients. Family sharing size." },
  { name: "Dam Pukh With Rice", category: "Special Dishes", price: 1800, description: "Slow-cooked meat and rice sealed in handi. Aromatic dum style cooking." },
  { name: "Matka Chicken Biryani", category: "Special Dishes", price: 2600, description: "Premium chicken biryani cooked and served in clay pot. Traditional Kohat style." },
  { name: "Arabian Mutton Mandi", category: "Special Dishes", price: 3400, description: "Yemeni-style tender mutton with spiced rice. Served with raita and salata." },
  { name: "Arabian Chicken Mandi", category: "Special Dishes", price: 2600, description: "Fragrant chicken mandi with Arabian spices. Authentic Gulf taste." },
  { name: "Matka Beef Bannu Pulao", category: "Special Dishes", price: 3200, description: "Famous Bannu-style beef pulao in clay pot. Rich and flavorful." },
  { name: "Bannu Painda", category: "Special Dishes", price: 1200, description: "Traditional Bannu-style meat and bread dish. Served with broth." },
  { name: "Platter", category: "Special Dishes", price: 3700, description: "Mixed platter with BBQ, karahi, rice, and naan. Perfect for groups." },
  { name: "Shinwari Mutton Karahi", category: "Karahi", price: 1600, description: "Traditional Shinwari-style mutton karahi with tomatoes and green chilies." },
  { name: "Namkeen Mutton Karahi", category: "Karahi", price: 1600, description: "Salted mutton karahi with simple spices. Authentic Peshawari taste." },
  { name: "Mutton Karahi Special", category: "Karahi", price: 1700, description: "Signature mutton karahi with chef's special masala. Rich gravy." },
  { name: "Shinwari Chicken Karahi", category: "Karahi", price: 900, description: "Chicken karahi cooked Shinwari style. Fresh and flavorful." },
  { name: "Seekh Kabab Karahi", category: "Karahi", price: 850, description: "Grilled seekh kababs cooked in karahi gravy. Unique fusion." },
  { name: "White Chicken Karahi", category: "Karahi", price: 950, description: "Creamy white gravy chicken karahi with yogurt and mild spices." },
  { name: "Matka Koila Shinwari Karahi", category: "Karahi", price: 1100, description: "Charcoal-infused Shinwari karahi served in clay pot. Smoky aroma." },
  { name: "Mutton Tikka Champ", category: "B.B.Q", price: 1550, description: "Tender mutton chops marinated in spices. Charcoal grilled." },
  { name: "Mutton Tikka Boneless", category: "B.B.Q", price: 2400, description: "Boneless mutton pieces marinated with special spices. Soft and juicy." },
  { name: "Chicken Tikka Namkeen", category: "B.B.Q", price: 320, description: "Salted chicken tikka with simple spices. Traditional taste." },
  { name: "Chicken Tikka Masala", category: "B.B.Q", price: 320, description: "Spicy masala chicken tikka. Charcoal grilled perfection." },
  { name: "Special Chicken Angara", category: "B.B.Q", price: 1400, description: "Whole chicken marinated in fiery spices. Served on charcoal grill." },
  { name: "Silver Fish Fry", category: "B.B.Q", price: 990, description: "Fresh silver fish marinated and fried or grilled. Seafood delight." },
  { name: "Rao Fish Fry", category: "B.B.Q", price: 990, description: "Rao fish prepared with chef's special marinade. Soft and flavorful." },
  { name: "Simon Fish", category: "B.B.Q", price: 1300, description: "Fresh simon fish grilled with spices. Kohat specialty." },
  { name: "Seekh Kabab", category: "B.B.Q", price: 380, description: "Minced beef kababs grilled on skewers. Served with chutney." },
  { name: "Reshmi Kabab", category: "B.B.Q", price: 420, description: "Creamy and soft chicken kababs. Mild and rich flavor." },
  { name: "Gola Kabab", category: "B.B.Q", price: 400, description: "Round minced beef kababs. Spicy and juicy." },
  { name: "Beef Tikka", category: "B.B.Q", price: 450, description: "Cubed beef tikka marinated in special spices. Charcoal grilled." },
  { name: "Chicken Malai Boti", category: "B.B.Q", price: 420, description: "Creamy chicken boti with mild spices. Soft and tender." },
  { name: "Chicken Boti", category: "B.B.Q", price: 380, description: "Spicy chicken boti cubes. Perfect BBQ appetizer." },
  { name: "Lahori Charga", category: "B.B.Q", price: 1500, description: "Whole fried chicken marinated in Lahori spices. Crispy outside juicy inside." },
  { name: "Fish Angara", category: "B.B.Q", price: 1100, description: "Grilled fish with angara charcoal smokiness. Served with mint chutney." },
  { name: "Mutton White Handi", category: "Handi", price: 1800, description: "Mutton cooked in creamy white gravy with yogurt and nuts." },
  { name: "Mutton Red Handi", category: "Handi", price: 1800, description: "Spicy red mutton handi with tomatoes and Kashmiri chilies." },
  { name: "Special Mutton Handi", category: "Handi", price: 1950, description: "Signature mutton handi with chef's secret masala. Rich and aromatic." },
  { name: "Chicken Red Handi", category: "Handi", price: 1050, description: "Spicy red gravy chicken handi. Perfect with naan." },
  { name: "Chicken White Handi", category: "Handi", price: 1300, description: "Creamy white chicken handi with mild spices. Family favorite." },
  { name: "Special Chicken Handi", category: "Handi", price: 1200, description: "Chef's special chicken handi. Balanced spices and rich gravy." }
];

const seedFullMenu = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    
    // Clear existing menu items first for a clean state
    await MenuItem.deleteMany({});
    
    const formattedItems = items.map(item => ({
      ...item,
      category: categoryMap[item.category],
      image: { url: 'https://images.unsplash.com/photo-1544025162-d76694265947', publicId: 'none' }, // Bulk placeholder
      isPopular: item.price > 1000,
      isAvailable: true
    }));

    await MenuItem.insertMany(formattedItems);
    console.log(`Success! Inserted ${formattedItems.length} items into the Texas Grill database.`);
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seedFullMenu();
